# These formatting rules to try conform the Substrate style guidelines:
# >   https://wiki.parity.io/Substrate-Style-Guide

reorder_imports = true
hard_tabs = true
max_width = 100

license_template_path = "FILE_TEMPLATE"
