[package]
authors = ["PureStake"]
edition = "2018"
name = "pallet-ethereum-chain-id"
version = "0.1.0"

[dependencies]
parity-scale-codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true, features = ["derive"] }

frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "rococo-branch" }

[features]
default = ["std"]
std = [
    "parity-scale-codec/std",
    "serde",
    "frame-support/std",
    "frame-system/std",
]
